### ISSUE TITLE
Is OpenLeg Open?

### ISSUE THREAD

**Issue by abetusk** [JoeyByrnes/OpenLeg#1]
Is `OpenLeg` "open source"? If so, what is the license of all of the digital artifacts, including source code, STL files and documentation (PDF, etc.)?

If the intent is to make this open source, could you please provide a `LICENSE` file and a description of what license you would like each of the components to fall under?

Without an explicit license, all work falls under copyright and cannot be considered "open source". Unfortunately, the copyright system is "opt-out" rather than "opt-in" so one must explicitly give a license that gives open source permissions on the source code and other digital artifacts.

[Open Source](https://en.wikipedia.org/wiki/Open-source_license) has a commonly accepted definition of:

> ... products that allows the source code, blueprint or design to be used, modified and/or shared ... . This allows **end users and commercial companies to review and modify the source code**, blueprint or design for their own customization, curiosity or troubleshooting needs. ... Licenses which only permit **non-commercial redistribution or modification of the source code for personal use only are generally not considered as open-source licenses**. 

Where the emphasis is mine.

I want to be clear: this is your work. If you would like to make it proprietary, this is obviously well within your rights but I would ask to please not confuse the community by claiming it's "open source" or have the project name include the word "open".

If the intent is to open source this project, please provide the required license terms.

**Comment by JoeyByrnes** [comment]
Thank you, I just added the MIT License to the repository.
