### ISSUE TITLE
Feedback for future

### ISSUE THREAD

**Issue by casainho** [JoeyByrnes/OpenLeg#2]
Hi.

I don't know where to give feedback so I am opening this issue.

As an user I dream to have a 4 leg walking robot of the medium size dog, that could follow me when I am walking or riding my bicycle. Maybe I am dream to much... Anyway, we need projects like OpenTorque and OpenLeg to make this a reality, so, many thanks for developing and sharing OpenLeg.

I also started the ELegs project, where I want to develop and build for my own an electric legs/exoskeleton with focus on sports for walking and running, just like I do now to go outside and ride my ebike, in future I want to go outside and run and walk using the ELegs: https://github.com/elegs/elegs/wiki

So, many thank you and please keep developing OpenLeg. We know that 3D printing is very accessible now, as also electronics and tools and libraries to develop the software, so, should be possible to develop and build our own walking robots as RepRap community did for 3D printers, Arduino, etc!!

**Comment by JoeyByrnes** [comment]
Thanks for the feedback. I am absolutely continuing to develop this project, this is just the start.
